name: sipos-prod

services:
  app:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    container_name: sipos_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - sipos_storage:/var/www/html/storage
      - sipos_build_assets:/var/www/html/public/build
      - ./docker/prod/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    env_file:
      - .env.production
    networks:
      - sipos_network
    depends_on:
      - mariadb
      - redis

  nginx:
    image: nginx:1.25-alpine
    container_name: sipos_nginx
    restart: always
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - ./public:/var/www/html/public:ro
      - sipos_storage:/var/www/html/storage:ro
      - sipos_build_assets:/var/www/html/public/build:ro
      - ./docker/prod/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sipos_network
    depends_on:
      - app

  mariadb:
    image: mariadb:11
    container_name: sipos_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MARIADB_DATABASE: sipos_prod
      MARIADB_USER: sipos
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    volumes:
      - sipos_db_data:/var/lib/mysql
    networks:
      - sipos_network

  redis:
    image: redis:7-alpine
    container_name: sipos_redis
    restart: always
    volumes:
      - sipos_redis_data:/data
    networks:
      - sipos_network

  worker:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    container_name: sipos_worker
    restart: always
    working_dir: /var/www/html
    command: php artisan queue:work redis --sleep=3 --tries=3 --max-time=3600
    env_file:
      - .env.production
    networks:
      - sipos_network
    depends_on:
      - mariadb
      - redis

  scheduler:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    container_name: sipos_scheduler
    restart: always
    working_dir: /var/www/html
    command: sh -c "while true; do php artisan schedule:run --verbose --no-interaction; sleep 60; done"
    env_file:
      - .env.production
    networks:
      - sipos_network
    depends_on:
      - mariadb
      - redis

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: sipos_tunnel
    restart: always
    command: tunnel --no-autoupdate run --token eyJhIjoiMTEwOTZlZGY3MDIzNmVkN2ZhZWY2YWU5YTZjZmY3YzgiLCJ0IjoiOTc1ZjY1OTMtNjcwMC00OTcwLWI2YzAtMjcwMjBkZGRlZjIxIiwicyI6Ik16RTFOak00TXpZdE5EZ3pOQzAwTXpoa0xUa3dPV010WWpoaE9UazBZbUZpTUdZMyJ9
    networks:
      - sipos_network
    depends_on:
      - nginx

secrets:
  db_root_password:
    file: ./docker/secrets/db_root_password.txt
  db_password:
    file: ./docker/secrets/db_password.txt

volumes:
  sipos_db_data:
  sipos_storage:
  sipos_redis_data:
  sipos_build_assets:

networks:
  sipos_network:
    driver: bridge
